### ISSUE TITLE
spring_amr module not found error

### ISSUE THREAD

**Issue by kanchanks** [jcyk/XAMR#1]
@jcyk, Hi I am new to working with repositories on git. Can you help me with this issue.

Steps followed:
1. Install libraries from requirement.txt
2. Run evaluation script work.sh with the pre-trained model (best.pt provided in google drive).
Facing error spring_amr 

Traceback (most recent call last):
  File "../input/xamrmain/XAMR-main/bin/predict_amrs.py", line 7, in <module>
    from spring_amr import ROOT
ModuleNotFoundError: No module named 'spring_amr'

**Comment by jcyk** [comment]
Hi @kanchanks. Thanks for your interests in our work. Make sure you are using python3 and you are running scripts from the main directory.

**Comment by kanchanks** [comment]
@jcyk Thank you for your response. It was the directory issue! I was able to solve it by adding the directory to sys.path

I also wanted to know what script I must run to generate AMR for new multi-lingual data using the pre-trained model? As this is not very clear in the instructions provided.
