### ISSUE TITLE
can't run the model and get non-zero results

### ISSUE THREAD

**Issue by meganndare** [jcyk/XAMR#3]
Hi! I am trying to use your parser to parse some english and chinese sentences into AMR trees. I would like to use the pretrained best.pt model you provide a link to on your readme.

I have gotten the model downloaded and set up, but when I run it and point the `dataset` to my text file, the results basically aren't generating any AMR trees. I have also tried pointing to the `amr-release-2.0-amrs-test-proxy.sentences.{lang}.txt` files incase there was a problem with my file's format, but the output looks similar. I'm including some examples at the bottom.

Do you have any ideas or could provide some more clarity on how I could parse a text file of my own sentences? Any help would be appreciated!

`2023-01-19 21:31:32,408 ignite.distributed.launcher.Parallel INFO: Initialized distributed launcher with backend: 'nccl'`

`2023-01-19 21:31:32,408 ignite.distributed.launcher.Parallel INFO: - Parameters to spawn processes:
        nproc_per_node: 1
        nnodes: 1
        node_rank: 0
        master_port: 8888`

`2023-01-19 21:31:32,408 ignite.distributed.launcher.Parallel INFO: Spawn function '<function run at 0x7f9d8f564b70>' in 1 processes
0it [00:00, ?it/s]`

`2023-01-19 21:32:37,741 Data Loading INFO: the number of instances 0, discarded 0, too long 0
rank 0: 0it [00:00, ?it/s]
Error: File 1 has less AMRs than file 2
Ignoring remaining AMRs
ckpt/best.pt ['/home/CE/code/XAMR/xl-amr/data/AMR/amr_2-four_translations/data/amr-release-2.0-amrs-test-proxy.sentences.DE.txt']
Smatch: 0.0`

`2023-01-19 21:32:38,512 ignite.distributed.launcher.Parallel INFO: End of run`

(my `work.sh` looks as in github with the exception of the dataset directory and number of processes per node)

**Comment by jcyk** [comment]
Hi @meganndare ,

Could you please provide some examples in your `dataset` in `work.sh`?

**Comment by jcyk** [comment]
anyway, I have added more detailed explanations in README. Hope it helps!

**Comment by meganndare** [comment]
Hi @jcyk : The data format was indeed my issue -- thank you so much for adding the more detailed documentation, I can now get real AMR parse trees!
